name: Docker Image CI

env:
  IMAGE_TAG: romaxa55/iptv-restreamer:latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


   - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: romaxa55/iptv-restreamer:latest

  - name: Start Docker container
      run: docker run --rm -d -p 8000:8000 ${{ env.IMAGE_TAG }}

  - name: Run integration tests
    uses: actions/checkout@v3
    with:
      repository: romaxa55/iptv-restreamer
      ref: main
      path: iptv

  - name: Install dependencies
    run: |
      cd iptv
      pip install -r requirements.txt
  - name: Run tests
    run: |
      cd iptv
      pytest test_app.py -v